uploadInfo <- function(){
  tekst <- "<h4><font color=\"#CC0000\">The Input Files.</font></h4>
  <br>
  This app is designed to be analysing data from the realtime machine we are using here.
  So for now it only accepts excel files (.xml, .xmlx) generated by the Quantstudio 3.
  <img src=\"real-time-pcr-500x500.jpg\">

  It is possible to select as many files as you want for the analysis. It is not checked for any 
  plate controls, so if you're afraid off plate to plate differences take this to account when 
  starting the experiment and try to keep all targets of a sample to one plate.
  <br><br>
  In the future we are planning to make this app suitable for more types of input. 
  "
  return(tekst)
}


outlayersInfo <- function(){
  tekst <- "<h4><font color=\"#2EAF2E\">Outlayers aka pipetting errors</font></h4>
  <br>
  Upon clicking the <font color=\"#2EAF2E\"><strong>outlayers</strong></font> button, a list of reactions is returned exceeding the user chosen threshold 
  of the difference between the highest and lowest CT value of technical replicates.
  <br><br>
  The outlayers are not removed but just given. So if you want to do something with the information 
  you will have to go back to the excel files and remove values manually.
  <br><br>
  Take note that samples with a higher CT value also tent to get higher errors. 
  "
  return(tekst)
}


targetsInfo <- function(){
  tekst <- "<h4><font color=\"#1C1CE3\"><br>The Targets (primerscombinations).</font></h4>"
  return(tekst)
}


refgeneInfo <- function(){
  tekst <- "<h4><font color=\"#F5A015\"><br>This will be containing info on what reference gene to use.</font></h4>"
  return(tekst)
}


refsampleInfo <- function(){
  tekst <- "<h4><font color=\"#AB2DC4\"><br>This will be containing info using a ref sample or not.</font></h4>"
  return(tekst)
}